public without sharing class DadataBank {

    public String name {public get; public set;}
    public String nameShort {public get; public set;}
    public String bic {public get; public set;}
    public String correspondentAccount {public get; public set;}
    public String okpo {public get; public set;}
    public String town {public get; public set;}
    public String address {public get; public set;}

}