/**
 * Created by pgolyakov on 2019-07-25.
 */
@isTest
private class PD_MetaDataCacheController_Test {
/*
    @isTest static void testConstructor() {
        Test.setMock(HttpCalloutMock.class, new PD_MetaDataCacheController_MOCK());
        PD_MetaDataCacheController cont = new PD_MetaDataCacheController();
        cont.getProfileApiList();
        cont.getLayoutList();
        PD_MetaDataCacheController.ApiLayout al = new PD_MetaDataCacheController.ApiLayout('String i', 'String n', 'String objn', 'String displayName');
    }

    @isTest static void testfillProfilesCache2() {
        Test.setMock(HttpCalloutMock.class, new PD_MetaDataCacheController_MOCK());
        PD_MetaDataCacheController.fillProfilesCache2('profileId', 'profileName');
    }

    @isTest static void testfillLayoutsCache2() {
        Test.setMock(HttpCalloutMock.class, new PD_MetaDataCacheController_MOCK());
        PD_MetaDataCacheController.fillLayoutsCache2('layoutId', 'layoutName');
    }
*/
}